x-default_env: &default_env
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/London"

x-default: &default
  restart: unless-stopped
  networks: 
    - backend

services:
  postgis:
    <<: *default
    image: postgis/postgis:16-3.4
    container_name: ${DB_HOST}-${TAG}
    environment:
      <<: *default_env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - pgdata:/var/lib/postgresql/data

  coffee-api:
    <<: *default
    image: coffee-api:${TAG}
    container_name: coffee-api-${TAG}
    environment:
      <<: *default_env
      API_PORT: ${API_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}-${TAG}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "${API_PORT}:80"
    volumes:
      - ${CONFIG_DIR}/coffee-api:/config
    depends_on:
      postgis:
        condition: service_healthy

  pgadmin:
    <<: *default
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pricegareth2@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  backend:
    name: coffee_network_${TAG}
    driver: bridge

volumes:
  pgdata:
  pgadmin-data: