FROM python:3.13.3-alpine

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN \
 apk add --no-cache postgresql-libs && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
 python3 -m pip install -r /code/requirements.txt --no-cache-dir && \
 apk --purge del .build-deps


COPY ./app /code/app

EXPOSE 9700

# Execute uvicorn in the Dockerfile
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]